version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    filters:
      branches:
        only:
          - master
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - run: npm run deploy

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
